#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : imlib2
Version  : 1.5.1
Release  : 10
URL      : https://sourceforge.net/projects/enlightenment/files/imlib2-src/1.5.1/imlib2-1.5.1.tar.bz2
Source0  : https://sourceforge.net/projects/enlightenment/files/imlib2-src/1.5.1/imlib2-1.5.1.tar.bz2
Summary  : Powerful image loading and rendering library
Group    : Development/Tools
License  : Imlib2
Requires: imlib2-bin
Requires: imlib2-lib
Requires: imlib2-license
Requires: imlib2-data
BuildRequires : bzip2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-shm)
BuildRequires : pkgconfig(xext)

%description
Imlib2 is an advanced replacement library for libraries like libXpm that
provides many more features with much greater flexibility and speed than
standard libraries, including font rasterization, rotation, RGBA space
rendering and blending, dynamic binary filters, scripting, and more.

%package bin
Summary: bin components for the imlib2 package.
Group: Binaries
Requires: imlib2-data
Requires: imlib2-license

%description bin
bin components for the imlib2 package.


%package data
Summary: data components for the imlib2 package.
Group: Data

%description data
data components for the imlib2 package.


%package dev
Summary: dev components for the imlib2 package.
Group: Development
Requires: imlib2-lib
Requires: imlib2-bin
Requires: imlib2-data
Provides: imlib2-devel

%description dev
dev components for the imlib2 package.


%package lib
Summary: lib components for the imlib2 package.
Group: Libraries
Requires: imlib2-data
Requires: imlib2-license

%description lib
lib components for the imlib2 package.


%package license
Summary: license components for the imlib2 package.
Group: Default

%description license
license components for the imlib2 package.


%prep
%setup -q -n imlib2-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533593738
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533593738
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/imlib2
cp COPYING %{buildroot}/usr/share/doc/imlib2/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/imlib2-config
/usr/bin/imlib2_bumpmap
/usr/bin/imlib2_colorspace
/usr/bin/imlib2_conv
/usr/bin/imlib2_grab
/usr/bin/imlib2_poly
/usr/bin/imlib2_show
/usr/bin/imlib2_test
/usr/bin/imlib2_view

%files data
%defattr(-,root,root,-)
/usr/share/imlib2/data/fonts/cinema.ttf
/usr/share/imlib2/data/fonts/grunge.ttf
/usr/share/imlib2/data/fonts/morpheus.ttf
/usr/share/imlib2/data/fonts/notepad.ttf
/usr/share/imlib2/data/images/audio.png
/usr/share/imlib2/data/images/bg.png
/usr/share/imlib2/data/images/bulb.png
/usr/share/imlib2/data/images/cal.png
/usr/share/imlib2/data/images/calc.png
/usr/share/imlib2/data/images/folder.png
/usr/share/imlib2/data/images/globe.png
/usr/share/imlib2/data/images/imlib2.png
/usr/share/imlib2/data/images/lock.png
/usr/share/imlib2/data/images/mail.png
/usr/share/imlib2/data/images/menu.png
/usr/share/imlib2/data/images/mush.png
/usr/share/imlib2/data/images/paper.png
/usr/share/imlib2/data/images/sh1.png
/usr/share/imlib2/data/images/sh2.png
/usr/share/imlib2/data/images/sh3.png
/usr/share/imlib2/data/images/stop.png
/usr/share/imlib2/data/images/tnt.png

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libImlib2.so
/usr/lib64/pkgconfig/imlib2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/imlib2/filters/bumpmap.so
/usr/lib64/imlib2/filters/colormod.so
/usr/lib64/imlib2/filters/testfilter.so
/usr/lib64/imlib2/loaders/argb.so
/usr/lib64/imlib2/loaders/bmp.so
/usr/lib64/imlib2/loaders/bz2.so
/usr/lib64/imlib2/loaders/ff.so
/usr/lib64/imlib2/loaders/jpeg.so
/usr/lib64/imlib2/loaders/lbm.so
/usr/lib64/imlib2/loaders/png.so
/usr/lib64/imlib2/loaders/pnm.so
/usr/lib64/imlib2/loaders/tga.so
/usr/lib64/imlib2/loaders/xpm.so
/usr/lib64/imlib2/loaders/zlib.so
/usr/lib64/libImlib2.so.1
/usr/lib64/libImlib2.so.1.5.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/imlib2/COPYING
