#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: da8b975
#
Name     : imlib2
Version  : 1.12.2
Release  : 33
URL      : https://sourceforge.net/projects/enlightenment/files/imlib2-src/1.12.2/imlib2-1.12.2.tar.xz
Source0  : https://sourceforge.net/projects/enlightenment/files/imlib2-src/1.12.2/imlib2-1.12.2.tar.xz
Summary  : Powerful image loading and rendering library
Group    : Development/Tools
License  : Imlib2
Requires: imlib2-bin = %{version}-%{release}
Requires: imlib2-data = %{version}-%{release}
Requires: imlib2-lib = %{version}-%{release}
Requires: imlib2-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : giflib-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : libwebp-dev
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-shm)
BuildRequires : xz-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Imlib2 1.12.2
This is the Imlib 2 library - a library that does image file loading and
saving as well as rendering, manipulation, arbitrary polygon support, etc.

%package bin
Summary: bin components for the imlib2 package.
Group: Binaries
Requires: imlib2-data = %{version}-%{release}
Requires: imlib2-license = %{version}-%{release}

%description bin
bin components for the imlib2 package.


%package data
Summary: data components for the imlib2 package.
Group: Data

%description data
data components for the imlib2 package.


%package dev
Summary: dev components for the imlib2 package.
Group: Development
Requires: imlib2-lib = %{version}-%{release}
Requires: imlib2-bin = %{version}-%{release}
Requires: imlib2-data = %{version}-%{release}
Provides: imlib2-devel = %{version}-%{release}
Requires: imlib2 = %{version}-%{release}

%description dev
dev components for the imlib2 package.


%package lib
Summary: lib components for the imlib2 package.
Group: Libraries
Requires: imlib2-data = %{version}-%{release}
Requires: imlib2-license = %{version}-%{release}

%description lib
lib components for the imlib2 package.


%package license
Summary: license components for the imlib2 package.
Group: Default

%description license
license components for the imlib2 package.


%prep
%setup -q -n imlib2-1.12.2
cd %{_builddir}/imlib2-1.12.2
pushd ..
cp -a imlib2-1.12.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707404710
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707404710
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/imlib2
cp %{_builddir}/imlib2-%{version}/COPYING %{buildroot}/usr/share/package-licenses/imlib2/4bb00a078e16718ff6547e7ec70b558a8dd3680a || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/imlib2_bumpmap
/V3/usr/bin/imlib2_colorspace
/V3/usr/bin/imlib2_conv
/V3/usr/bin/imlib2_grab
/V3/usr/bin/imlib2_load
/V3/usr/bin/imlib2_poly
/V3/usr/bin/imlib2_show
/V3/usr/bin/imlib2_test
/V3/usr/bin/imlib2_view
/usr/bin/imlib2_bumpmap
/usr/bin/imlib2_colorspace
/usr/bin/imlib2_conv
/usr/bin/imlib2_grab
/usr/bin/imlib2_load
/usr/bin/imlib2_poly
/usr/bin/imlib2_show
/usr/bin/imlib2_test
/usr/bin/imlib2_view

%files data
%defattr(-,root,root,-)
/usr/share/imlib2/data/fonts/cinema.ttf
/usr/share/imlib2/data/fonts/grunge.ttf
/usr/share/imlib2/data/fonts/morpheus.ttf
/usr/share/imlib2/data/fonts/notepad.ttf
/usr/share/imlib2/data/images/audio.png
/usr/share/imlib2/data/images/bg.png
/usr/share/imlib2/data/images/bulb.png
/usr/share/imlib2/data/images/cal.png
/usr/share/imlib2/data/images/calc.png
/usr/share/imlib2/data/images/folder.png
/usr/share/imlib2/data/images/globe.png
/usr/share/imlib2/data/images/imlib2.png
/usr/share/imlib2/data/images/lock.png
/usr/share/imlib2/data/images/mail.png
/usr/share/imlib2/data/images/menu.png
/usr/share/imlib2/data/images/mush.png
/usr/share/imlib2/data/images/paper.png
/usr/share/imlib2/data/images/sh1.png
/usr/share/imlib2/data/images/sh2.png
/usr/share/imlib2/data/images/sh3.png
/usr/share/imlib2/data/images/stop.png
/usr/share/imlib2/data/images/tnt.png
/usr/share/imlib2/rgb.txt

%files dev
%defattr(-,root,root,-)
/usr/include/Imlib2.h
/usr/include/Imlib2_Loader.h
/usr/lib64/libImlib2.so
/usr/lib64/pkgconfig/imlib2.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/imlib2/filters/bumpmap.so
/V3/usr/lib64/imlib2/filters/colormod.so
/V3/usr/lib64/imlib2/filters/testfilter.so
/V3/usr/lib64/imlib2/loaders/ani.so
/V3/usr/lib64/imlib2/loaders/argb.so
/V3/usr/lib64/imlib2/loaders/bmp.so
/V3/usr/lib64/imlib2/loaders/bz2.so
/V3/usr/lib64/imlib2/loaders/ff.so
/V3/usr/lib64/imlib2/loaders/gif.so
/V3/usr/lib64/imlib2/loaders/ico.so
/V3/usr/lib64/imlib2/loaders/jpeg.so
/V3/usr/lib64/imlib2/loaders/lbm.so
/V3/usr/lib64/imlib2/loaders/lzma.so
/V3/usr/lib64/imlib2/loaders/png.so
/V3/usr/lib64/imlib2/loaders/pnm.so
/V3/usr/lib64/imlib2/loaders/qoi.so
/V3/usr/lib64/imlib2/loaders/tga.so
/V3/usr/lib64/imlib2/loaders/webp.so
/V3/usr/lib64/imlib2/loaders/xbm.so
/V3/usr/lib64/imlib2/loaders/xpm.so
/V3/usr/lib64/imlib2/loaders/zlib.so
/V3/usr/lib64/libImlib2.so.1.12.2
/usr/lib64/imlib2/filters/bumpmap.so
/usr/lib64/imlib2/filters/colormod.so
/usr/lib64/imlib2/filters/testfilter.so
/usr/lib64/imlib2/loaders/ani.so
/usr/lib64/imlib2/loaders/argb.so
/usr/lib64/imlib2/loaders/bmp.so
/usr/lib64/imlib2/loaders/bz2.so
/usr/lib64/imlib2/loaders/ff.so
/usr/lib64/imlib2/loaders/gif.so
/usr/lib64/imlib2/loaders/ico.so
/usr/lib64/imlib2/loaders/jpeg.so
/usr/lib64/imlib2/loaders/lbm.so
/usr/lib64/imlib2/loaders/lzma.so
/usr/lib64/imlib2/loaders/png.so
/usr/lib64/imlib2/loaders/pnm.so
/usr/lib64/imlib2/loaders/qoi.so
/usr/lib64/imlib2/loaders/tga.so
/usr/lib64/imlib2/loaders/webp.so
/usr/lib64/imlib2/loaders/xbm.so
/usr/lib64/imlib2/loaders/xpm.so
/usr/lib64/imlib2/loaders/zlib.so
/usr/lib64/libImlib2.so.1
/usr/lib64/libImlib2.so.1.12.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/imlib2/4bb00a078e16718ff6547e7ec70b558a8dd3680a
